### ISSUE TITLE
About the MTCNN face detections and preprocessing

### ISSUE THREAD

**Issue by manisoftwartist** [visionjo/facerec-bias-bfw#54]
Hi, 

It would be great if you could clarify a few questions regarding this dataset please.

1.  Is it possible for you to provide the MTCNN output face detections (bounding boxes and facial landmarks) for the face samples in BFW?

2. Am I right in assuming MTCNN takes as input the images in "face-samples" folder of the dataset? If yes, what settings do we use with MTCNN in order for us to detect a face correctly on all the facial images provided in face-samples? If not, can you help us reproduce your face detection results by providing us with the original images on which the MTCNN was run to obtain the results in face-samples?

3. Are the images in facial-samples actually crops which are aligned?

Thanks in advance for your help.

**Comment by visionjo** [comment]
Greetings:

The face crops are detected using MTCNN and aligned via affine transformation. 

I will provide the key point coordinates, along with faces that are cropped but not aligned. This way, the aligned are available if preferred, but as too are non-aligned.

Thank you for pointing this out. Anything that comes to mind that could help make the resource more useful we are all about! 

I will be in touch as soon as some of (or all of) the parts are ready.

**Comment by visionjo** [comment]
@manisoftwartist, now available are the unprocessed facial images, along with the output of MTCNN (i.e., BB coordinates, along with 5 key-points (x, y)).

The image list should be the same. 

We planned to use GoogleDrive for other reasons, so access here now https://forms.gle/fsLRyAN1MuLuhzRZA. 

The folder of face directories, along with the detections (as dict), are used in this script just as provided on Drive [see https://github.com/visionjo/facerec-bias-bfw/blob/0d55300078928c51632fba19127ed3bdbe35d196/code/python_scripts/align_faces_5pts_affine.py#L21]

I hope this helps and let me know how everything goes!
